const tours = [
  {
    id: 1,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 2,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 3,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 4,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 5,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 6,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 7,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 8,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 9,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 10,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 11,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
  {
    id: 12,
    image: "@/assets/img/image_11.png",
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
  },
];

export const data = { tours };
