const tours = [
  {
    id: 1,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 2,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 3,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 4,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 5,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 6,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 7,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 8,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 9,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 10,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 11,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
  {
    id: 12,
    image: require("@/assets/img/image_11.png"),
    name: "ยุโรป ตะวันออก",
    days: 8,
    nights: 5,
    price: 49888,
    countries: ["ออสเตรเลีย", "เชค", "สโลวัก", "ฮังการี"],
    airline: "EVA Air",
    details: "",
  },
];

export const data = { tours };
