import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faFacebook,
  faSquareFacebook,
  faInstagram,
  faTwitter,
  faLine,
  faFacebookMessenger,
} from "@fortawesome/free-brands-svg-icons";

import {
  faMagnifyingGlass,
  faCircleXmark as solidCircleXmark,
  faLocationDot,
  faClock,
  faPlane,
  faBus,
  faPhone,
  faEnvelope,
  faPlus,
  faPen,
  faTrash,
  faChevronUp,
  faChevronDown,
  faChevronCircleUp,
  faChevronCircleDown,
  faTimes,
  faCheck,
  faXmark,
  faLock,
  faBars,
  faExclamationCircle,
  faSignOutAlt,
  faSignOut,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircleXmark as regularCircleXmark,
  faUser,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faFacebook,
  faSquareFacebook,
  faBus,
  faPhone,
  faEnvelope,
  faLine,
  faInstagram,
  faTwitter,
  faMagnifyingGlass,
  faFacebookMessenger,
  solidCircleXmark,
  faLocationDot,
  faClock,
  faPlane,
  faPlus,
  faPen,
  faTrash,
  faChevronUp,
  faChevronDown,
  faChevronCircleUp,
  faChevronCircleDown,
  faTimes,
  regularCircleXmark,
  faCheck,
  faXmark,
  faBars,
  faExclamationCircle,
  faLock,
  faUser,
  faSignOutAlt,
  faSignOut
);
